
plugins: ['jekyll/scholar','rdiscount','jekyll-org-mode-converter']

highlighter: rouge
markdown: kramdown

exclude: ['README.org']

scholar:
  style: chicago-author-date
  locale: en

  sort_by: none
  order: reverse

  source: ./_bibliography
  bibliography: rademaker.bib

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"  
